name: dart_client_example
description: A sample command-line application.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.0.3

dependencies:
  data_models:
    path: ../../packages/data_models
  dio: ^5.3.3
  flutter_hive_offline_data_sync_demo:
    path: ../..
  hive: ^2.2.3
  uuid: ^4.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
