name: flutter_hive_offline_data_sync_demo
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.3

dependencies:
  hive: ^2.2.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
